name: promodoor
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.4







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0
  audioplayers: ^5.2.1
  percent_indicator: ^4.2.5
  provider: ^6.1.1
  firebase_core: ^3.10.1
  google_sign_in: ^6.2.2
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.0.1
  intl: ^0.18.1 # for date formatting





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/sounds/over_focus.mp3
    - assets/sounds/start_focus.mp3
    - assets/sounds/start_revision.mp3
    - assets/sounds/over_revision.mp3
    - assets/sounds/start_break.mp3
    - assets/sounds/over_break.mp3
    - assets/images/google.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
