// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATTwd8Zw54hs5jZiczsyt2X6jVjIqQkmI',
    appId: '1:219608580090:web:88b65604721ee54da26e43',
    messagingSenderId: '219608580090',
    projectId: 'timer-app-db3c4',
    authDomain: 'timer-app-db3c4.firebaseapp.com',
    storageBucket: 'timer-app-db3c4.firebasestorage.app',
    measurementId: 'G-RX000EKV31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlFvCEqsDyiOGDDXMhHN1vLSRo3DCVErI',
    appId: '1:219608580090:android:2ec6d9ca99f37b72a26e43',
    messagingSenderId: '219608580090',
    projectId: 'timer-app-db3c4',
    storageBucket: 'timer-app-db3c4.firebasestorage.app',
  );
}
